### ISSUE TITLE
No longer working

### ISSUE THREAD

**Issue by CharlieS1103** [RazorSh4rk/random-word-api#16]
The following link returns this error
https://random-word-api.herokuapp.com/word?number=1&swear=0
```java.lang.NoClassDefFoundError: Could not initialize class play.api.libs.json.Writes$
	at Main$.getWord(Main.scala:111)
	at Main$.$anonfun$new$18(Main.scala:86)
	at cask.router.Result$Success.map(Result.scala:21)
	at cask.router.Result$Success.map(Result.scala:20)
	at Main$.$anonfun$new$10(Main.scala:86)
	at cask.router.EntryPoint.invoke(EntryPoint.scala:46)
	at cask.router.Decorator$.$anonfun$invoke$2(Decorators.scala:58)
	at cask.endpoints.WebEndpoint.wrapFunction(WebEndpoints.scala:14)
	at cask.endpoints.WebEndpoint.wrapFunction$(WebEndpoints.scala:12)
	at cask.endpoints.get.wrapFunction(WebEndpoints.scala:31)
	at cask.router.Decorator$.invoke(Decorators.scala:52)
	at cask.main.Main$DefaultHandler.handleRequest(Main.scala:99)
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:360)
	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:830)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
```

**Comment by RazorSh4rk** [comment]
Thanks a lot for reporting! I kicked the dynos, and it works for me now, could you please verify that its okay for you too?

**Comment by CharlieS1103** [comment]
@RazorSh4rk Sure will do so as soon as i get back from school

**Comment by Sukadia** [comment]
It's back up and working for me, thanks for the constant maintenance!
